version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "password_encryption=scram-sha-256"]

volumes:
  postgres_data: 